version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ems-sqlserver
    environment:
      SA_PASSWORD: "StrongPass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1500:1433"
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d

  backend:
    image: ems-backend
    container_name: ems-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=master;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: StrongPass123

  frontend:
    image: ems-frontend
    container_name: ems-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080
